version: '3.9'

services:
  client:
    container_name: ski-resort-client
    image: ski-resort-client
    build:
      context: .
      dockerfile: docker/react.dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=true
