export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as Information } from './Information'
export { default as Employees } from './Employees';
export { default as CreateEmployee} from './CreateEmployee';
export { default as EditEmployee} from './EditEmployee';
export { default as Guests} from './Guests';
export { default as CreateGuest} from './CreateGuest';
export { default as EditGuest} from './EditGuest';
export { default as Dishes} from './Dishes';
export { default as CreateDish} from './CreateDish';
export { default as EditDish} from './EditDish';
export { default as Desserts} from './Desserts';
export { default as CreateDessert} from './CreateDessert';
export { default as EditDessert} from './EditDessert';
export { default as Gear} from './Gear';
export { default as CreateGear} from './CreateGear';
export { default as EditGear} from './EditGear';
export { default as Localizations} from './Localizations';
export { default as CreateLocalization} from './CreateLocalization';
export { default as EditLocalization} from './EditLocalization';
export { default as Tasks} from './Tasks';
export { default as CreateTask} from './CreateTask';
export { default as EditTask} from './EditTask';
export { default as Rooms} from './Rooms';
export { default as CreateRoom} from './CreateRoom';
export { default as EditRoom} from './EditRoom';
export { default as Reservations } from './Reservations';
export { default as CreateReservation } from './CreateReservation';
export { default as EditReservation } from './EditReservation';
