export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as Information } from './Information'
export { default as Employees } from './Employees/Employees';
export { default as CreateEmployee} from './Employees/CreateEmployee';
export { default as EditEmployee} from './Employees/EditEmployee';
export { default as Guests} from './Guests/Guests';
export { default as CreateGuest} from './Guests/CreateGuest';
export { default as EditGuest} from './Guests/EditGuest';
export { default as Dishes} from './Dishes/Dishes';
export { default as CreateDish} from './Dishes/CreateDish';
export { default as EditDish} from './Dishes/EditDish';
export { default as Desserts} from './Desserts/Desserts';
export { default as CreateDessert} from './Desserts/CreateDessert';
export { default as EditDessert} from './Desserts/EditDessert';
export { default as Gear} from './Gear/Gear';
export { default as CreateGear} from './Gear/CreateGear';
export { default as EditGear} from './Gear/EditGear';
export { default as Localizations} from './Localizations/Localizations';
export { default as CreateLocalization} from './Localizations/CreateLocalization';
export { default as EditLocalization} from './Localizations/EditLocalization';
export { default as Tasks} from './Tasks/Tasks';
export { default as CreateTask} from './Tasks/CreateTask';
export { default as EditTask} from './Tasks/EditTask';
export { default as Rooms} from './Rooms/Rooms';
export { default as CreateRoom} from './Rooms/CreateRoom';
export { default as EditRoom} from './Rooms/EditRoom';
export { default as Reservations } from './Reservations/Reservations';
export { default as CreateReservation } from './Reservations/CreateReservation';
export { default as EditReservation } from './Reservations/EditReservation';
export { default as Rental } from './Rental/Rental';
export { default as EditRental } from './Rental/EditRental';
export { default as CreateRental } from './Rental/CreateRental';
export { default as Meals } from './Meals/Meals';
export { default as EditMeal } from './Meals/EditMeal';
export { default as CreateMeal } from './Meals/CreateMeal';