# Generated by Django 4.0 on 2022-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Task description', max_length=128)),
                ('beds', models.IntegerField(blank=True, help_text='Number of beds in a room', null=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Price of the room', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='user full name', max_length=64, unique=True)),
                ('role', models.CharField(blank=True, help_text='user role', max_length=32, null=True)),
            ],
        ),
    ]
