# Generated by Django 4.0 on 2022-12-28 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiresort', '0002_employee_guest_room_room_id_room_wing_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='social_security_number',
            field=models.IntegerField(help_text='Polish social security number PESEL', validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
