# Generated by Django 4.0 on 2022-12-30 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiresort', '0005_alter_employee_social_security_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('calories', models.PositiveIntegerField()),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('calories', models.PositiveIntegerField()),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(help_text='Polish social security number PESEL', max_length=11),
        ),
        migrations.AlterField(
            model_name='guest',
            name='social_security_number',
            field=models.CharField(help_text='Polish social security number PESEL', max_length=11),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(help_text='Number of beds in a room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(help_text='Price of the room', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='wing',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='skiresort.employee')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='skiresort.gear')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='skiresort.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_day', models.CharField(max_length=128)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='skiresort.dessert')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='skiresort.dish')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='skiresort.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='skiresort.employee')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='skiresort.localization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='skiresort.task')),
            ],
        ),
    ]
