# Generated by Django 4.0 on 2022-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiresort', '0006_dessert_dish_gear_localization_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(),
        ),
    ]
