# Generated by Django 4.0 on 2023-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiresort', '0008_remove_room_id_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(help_text='Polish social security number PESEL', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='social_security_number',
            field=models.CharField(help_text='Polish social security number PESEL', max_length=11, unique=True),
        ),
    ]
