# Generated by Django 4.0 on 2023-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiresort', '0009_alter_employee_social_security_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
