name: CI/CD for backend
on:
  push:
    paths:
        - server/**
  pull_request:
    branches:
      - main
    paths:
        - server/**

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: 'Create env file'
        working-directory: ./server
        run: |
          touch .env
          echo APP_PORT=8080 >> .env
          echo APP_CONTAINER_NAME="django" >> .env
      - name: "Build and run container"
        working-directory: ./server
        env:
          APP_PORT: 8080
          APP_CONTAINER_NAME: django
        run: docker-compose up -d --build

      - name: "Sleep for 30 seconds"
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: "Run tests"
        working-directory: ./server
        run: docker-compose exec -T django pytest

      - name: "Stop containers"
        working-directory: ./server
        run: docker-compose down
